POST /payment-orders HTTP/1.1
Host: localhost:8080
Content-Type: application/xml

<?xml version="1.0" encoding="utf-8" ?>
<PutLegalPaymentOrderRq>
    <payerAccountInfoBankInfoVSPNum>38903801775</payerAccountInfoBankInfoVSPNum>
    <docRef>78465654673534</docRef>
    <operationType>3</operationType>
    <cmsBase64>srEdsfsdvs534sdfg54gfgdf</cmsBase64>
</PutLegalPaymentOrderRq>

###

GET /payment-orders/2 HTTP/1.1
Host: localhost:8080

###

GET /payment-orders/doc-ref/78465654673534 HTTP/1.1
Host: localhost:8080

###

GET /holds/1 HTTP/1.1
Host: localhost:8080